CREATE MATERIALIZED VIEW avengers AS
SELECT EMP_ID
EMP_NAME FROM
EMPLOYEES
WHERE EMP_ID = 101;

select * from avengers;

REFRESH MATERIALIZED VIEW avengers;
CREATE MATERIALIZED VIEW new_avengers AS
SELECT EMP_ID
EMP_NAME FROM
EMPLOYEES
WHERE EMP_ID = 101
WITH NO DATA;


REFRESH MATERIALIZED VIEW new_avengers;


SELECT * FROM new_avengers;
